appname="工程"
appver="1.1.1"
packagename="com.androlua.plugin"
theme="Theme_Holo_Wallpaper"
developer="nirenr"
description="工程管理"
debugmode=true
mode="plugin"
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
