appname="布局助手"
appver="1.1"
packagename="com.androlua.layouthelper"
theme="Theme_Holo"
developer="nirenr"
description="快速布局工具"
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
