appname="工程属性"
appver="1.0"
packagename="com.androlua.projectinfo"
theme="Theme_Holo_Light"
developer="nirenr"
description="工程属性查看修改"
debugmode=true
user_permission={
  "INTERNET",
  "WRITE_EXTERNAL_STORAGE"
}
